version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PASSWORD_DUMY
      - POSTGRES_USER=USER_DUMY
      - POSTGRES_DB=DB_DUMMY
    ports:
      - 5433:5432