version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=rishikesh
      - POSTGRES_DB=neurelo_db
    ports:
      - 5433:5432